Repository y0014984/Advanced-Equipment, pull requests merged in 2023-02, with the labels that each got.

#324 Localization (CHS) Chinese Simplified for 0.5.2
  addons/armaos/stringtable.xml
  addons/filesystem/stringtable.xml
  addons/flashdrive/stringtable.xml
  addons/interaction/stringtable.xml
  addons/main/stringtable.xml
Labels: enhancement, localization

#323 added missing localization strings and updated translations
  AUTHORS.txt
  addons/armaos/CfgGames.hpp
  addons/armaos/functions/fnc_games_snake.sqf
  addons/armaos/functions/fnc_os_cat.sqf
  addons/armaos/functions/fnc_os_chown.sqf
  addons/armaos/functions/fnc_os_crack.sqf
  addons/armaos/functions/fnc_os_crypto.sqf
  addons/armaos/functions/fnc_os_echo.sqf
  addons/armaos/functions/fnc_os_history.sqf
  addons/armaos/functions/fnc_os_ls.sqf
  addons/armaos/functions/fnc_shell_getOpts.sqf
  addons/armaos/functions/fnc_shell_getOptsPrintHelp.sqf
  addons/armaos/stringtable.xml
  addons/filesystem/stringtable.xml
  addons/flashdrive/CfgWeapons.hpp
  addons/flashdrive/stringtable.xml
  addons/interaction/functions/fnc_animateInteraction.sqf
  addons/interaction/stringtable.xml
  addons/main/functions/fnc_3den_checkConnection.sqf
  addons/main/functions/fnc_initDebugOverlay.sqf
  addons/main/stringtable.xml
  addons/network/stringtable.xml
  addons/power/stringtable.xml
Labels: enhancement, localization

#327 Latest Bugfixes v0.5.2
  addons/armaos/functions/fnc_os_echo.sqf
  addons/armaos/functions/fnc_terminal_getAllowedKeysFR.sqf
  addons/armaos/functions/fnc_terminal_getAllowedKeysUS.sqf
  addons/armaos/stringtable.xml
Labels: bug, armaOS

#331 Fix for mv and cp syntax
  addons/filesystem/functions/fnc_mvObj.sqf
Labels: bug, armaOS

#329 Advanced Equipment v0.5.2 final
  AUTHORS.txt
  addons/armaos/CfgGames.hpp
  addons/armaos/functions/fnc_games_snake.sqf
  addons/armaos/functions/fnc_os_cat.sqf
  addons/armaos/functions/fnc_os_chown.sqf
  addons/armaos/functions/fnc_os_crack.sqf
  addons/armaos/functions/fnc_os_crypto.sqf
  addons/armaos/functions/fnc_os_echo.sqf
  addons/armaos/functions/fnc_os_history.sqf
  addons/armaos/functions/fnc_os_ls.sqf
  addons/armaos/functions/fnc_shell_getOpts.sqf
  addons/armaos/functions/fnc_shell_getOptsPrintHelp.sqf
  addons/armaos/functions/fnc_terminal_getAllowedKeysFR.sqf
  addons/armaos/functions/fnc_terminal_getAllowedKeysUS.sqf
  addons/armaos/stringtable.xml
  addons/filesystem/functions/fnc_mvObj.sqf
  addons/filesystem/stringtable.xml
  addons/flashdrive/CfgWeapons.hpp
  addons/flashdrive/stringtable.xml
  addons/interaction/functions/fnc_animateInteraction.sqf
  addons/interaction/stringtable.xml
  addons/main/functions/fnc_3den_checkConnection.sqf
  addons/main/functions/fnc_initDebugOverlay.sqf
  addons/main/stringtable.xml
  addons/network/stringtable.xml
  addons/power/stringtable.xml
Labels: bug

#336 Italian keyboard layout and localization
  AUTHORS.txt
  addons/armaos/XEH_PREP.hpp
  addons/armaos/XEH_preInit.sqf
  addons/armaos/functions/fnc_terminal_getAllowedKeysDE.sqf
  addons/armaos/functions/fnc_terminal_getAllowedKeysIT.sqf
  addons/armaos/functions/fnc_terminal_setKeyboardLayout.sqf
  addons/armaos/functions/fnc_terminal_switchKeyboardLayout.sqf
  addons/armaos/readme.md
  addons/armaos/stringtable.xml
  addons/filesystem/stringtable.xml
  addons/flashdrive/stringtable.xml
  addons/interaction/stringtable.xml
  addons/main/stringtable.xml
  addons/network/stringtable.xml
  addons/power/stringtable.xml
Labels: bug, enhancement, armaOS, terminal, localization

#337 More generators
  README.md
  addons/power/CfgVehicles.hpp
  addons/power/functions/fnc_getPowerOutput.sqf
  addons/power/sounds/GeneratorAirportRunningSound.ogg
  addons/power/sounds/GeneratorAirportStartSound.ogg
  addons/power/sounds/GeneratorAirportStopSound.ogg
  addons/power/sounds/GeneratorLargeRunningSound.ogg
  addons/power/sounds/GeneratorLargeStartSound.ogg
  addons/power/sounds/GeneratorLargeStopSound.ogg
  addons/power/stringtable.xml
Labels: enhancement, power
